Repository Jamesllllllllll/Daily-Dashboard, pull requests merged in 2024-01, with the labels that each got.

#41 standard node.js.yml file
  .github/workflows/node.js.yml
Labels: enhancement

#43 cleaned up eslint errors
  src/App.js
  src/components/QuoteOrFact/subComponents/Quote.js
  src/components/ShowHistory/ShowHistory.js
  src/components/WeatherForm/WeatherForm.jsx
  src/features/to-do-list/NewTask.js
  src/index.js
Labels: documentation

#44 Node.js cicd
  .github/workflows/node.js.yml
Labels: enhancement

#51 Fix weather form (& small fix to Quote component)
  src/components/QuoteOrFact/subComponents/Quote.js
  src/components/WeatherForm/WeatherForm.jsx
  src/routes/Home.jsx
Labels: bug

#59 Temp branch
  .env.example
  README.md
  src/components/ShowHistory/ShowHistory.js
Labels: documentation
